#define CLEAR_SCREEN    "\e[2J"
#define CURSOR_HOME	"\e[H"
#define CURSOR_LAST	"\e[%d;0H"
#define DEFAULT_COLORS  "\x1b[39;49m"
#define DRAW_TITLEBAR	"\x1b[2;44;44m "
#define DISPLAY_TITLE	"\e[1;%luH%s"
